version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["skip-changelog"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["skip-changelog"]

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily
